FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.1-stretch AS build
WORKDIR /src
COPY ["MSCars/MSCars.csproj", "MSCars/"]
RUN dotnet restore "MSCars/MSCars.csproj"
COPY . .
WORKDIR "/src/MSCars"
RUN dotnet build "MSCars.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "MSCars.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "MSCars.dll"]